userinfo = r'D:\program\oldmantest\quanzhan\day23\hw_guanli\db\userinfo'
teacher_obj = r'D:\program\oldmantest\quanzhan\day23\hw_guanli\db\teacher_obj'
schoolinfo = r'D:\program\oldmantest\quanzhan\day23\hw_guanli\db\schooleinfo'
course_obj = r'D:\program\oldmantest\quanzhan\day23\hw_guanli\db\course_obj'
classes_obj = r'D:\program\oldmantest\quanzhan\day23\hw_guanli\db\classes_obj'
studentinfo = r'D:\program\oldmantest\quanzhan\day23\hw_guanli\db\studentsinfo'